language: go
go:
  - 1.6
before_install:
  - go get -v github.com/golang/lint/golint
  - go get -v -t -d ./...
after_success:
  - make coverdata
  - bash <(curl -s https://codecov.io/bash)
script:
  - make -j4 check GOTEST_FLAGS=-v
