// Copyright (c) 2020 Arista Networks, Inc.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the COPYING file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: gnmireverse.proto

// Package gNMIReverse defines a service specification that reverses the
// direction of the dial for gNMI Subscribe and gNMI Get.
//
// gNMI is a "dial-in" service, where the telemetry collector must make a
// connection to the gNMI target. With gNMIReverse, a client can be run
// alongside the gNMI target and then "dial-out" to a gNMIReverse server
// to send streaming data.

package gnmireverse

import (
	gnmi "github.com/openconfig/gnmi/proto/gnmi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gnmireverse_proto protoreflect.FileDescriptor

const file_gnmireverse_proto_rawDesc = "" +
	"\n" +
	"\x11gnmireverse.proto\x12\vgnmireverse\x1a0github.com/openconfig/gnmi/proto/gnmi/gnmi.proto\x1a\x1bgoogle/protobuf/empty.proto2\x86\x01\n" +
	"\vgNMIReverse\x12<\n" +
	"\aPublish\x12\x17.gnmi.SubscribeResponse\x1a\x16.google.protobuf.Empty(\x01\x129\n" +
	"\n" +
	"PublishGet\x12\x11.gnmi.GetResponse\x1a\x16.google.protobuf.Empty(\x01B0Z.github.com/aristanetworks/goarista/gnmireverseb\x06proto3"

var file_gnmireverse_proto_goTypes = []any{
	(*gnmi.SubscribeResponse)(nil), // 0: gnmi.SubscribeResponse
	(*gnmi.GetResponse)(nil),       // 1: gnmi.GetResponse
	(*emptypb.Empty)(nil),          // 2: google.protobuf.Empty
}
var file_gnmireverse_proto_depIdxs = []int32{
	0, // 0: gnmireverse.gNMIReverse.Publish:input_type -> gnmi.SubscribeResponse
	1, // 1: gnmireverse.gNMIReverse.PublishGet:input_type -> gnmi.GetResponse
	2, // 2: gnmireverse.gNMIReverse.Publish:output_type -> google.protobuf.Empty
	2, // 3: gnmireverse.gNMIReverse.PublishGet:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gnmireverse_proto_init() }
func file_gnmireverse_proto_init() {
	if File_gnmireverse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gnmireverse_proto_rawDesc), len(file_gnmireverse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gnmireverse_proto_goTypes,
		DependencyIndexes: file_gnmireverse_proto_depIdxs,
	}.Build()
	File_gnmireverse_proto = out.File
	file_gnmireverse_proto_goTypes = nil
	file_gnmireverse_proto_depIdxs = nil
}
